# Generated by Django 4.2.1 on 2023-09-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account',
            field=models.IntegerField(choices=[(1, 'Basic'), (2, 'Premium'), (3, 'Enterprise')], default=1),
        ),
    ]
