# Generated by Django 4.2.1 on 2023-09-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0002_alter_profile_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='UserImage',
        ),
    ]
